//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoExamDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamInfo = new HashSet<ExamInfo>();
        }
    
        public int ExamID { get; set; }
        public int PaperID { get; set; }
        public int StuInfoID { get; set; }
        public Nullable<int> TeaInfoID { get; set; }
        public Nullable<int> ExamScore { get; set; }
        public Nullable<System.DateTime> ExamTime { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<System.DateTime> BatchTime { get; set; }
        public int ExamState { get; set; }
    
        public virtual Paper Paper { get; set; }
        public virtual StuInfo StuInfo { get; set; }
        public virtual TeaInfo TeaInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamInfo> ExamInfo { get; set; }
    }
}
