//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoExamDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InClassRecord
    {
        public int InClassRecordID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public string StuNo { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public Nullable<bool> IsResult { get; set; }
        public Nullable<int> State { get; set; }
        public System.DateTime RecordTime { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
