//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoExamDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StuInfo()
        {
            this.Exam = new HashSet<Exam>();
        }
    
        public int StuInfoID { get; set; }
        public string StuNo { get; set; }
        public string StuName { get; set; }
        public string StuDuty { get; set; }
        public bool StuSex { get; set; }
        public string StuPhoto { get; set; }
        public string StuAdd { get; set; }
        public string Remark { get; set; }
        public int ClassInfoID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ClassInfo ClassInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exam { get; set; }
    }
}
