//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoExamDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeaInfo()
        {
            this.Exam = new HashSet<Exam>();
        }
    
        public int TeaInfoID { get; set; }
        public string TeaNo { get; set; }
        public string TeaName { get; set; }
        public string TeaDuty { get; set; }
        public bool TeaSex { get; set; }
        public string TeaPhoto { get; set; }
        public string TeaAdd { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ClassInfoID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ClassInfo ClassInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exam { get; set; }
    }
}
