//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoExamDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.ExamInfo = new HashSet<ExamInfo>();
            this.InClassRecord = new HashSet<InClassRecord>();
            this.PaperInfo = new HashSet<PaperInfo>();
        }
    
        public int TopicID { get; set; }
        public string TopicExplain { get; set; }
        public int TopicType { get; set; }
        public string TopicA { get; set; }
        public string TopicB { get; set; }
        public string TopicC { get; set; }
        public string TopicD { get; set; }
        public int TopicSort { get; set; }
        public string TopicAnswer { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> EduTypeID { get; set; }
    
        public virtual CourseInfo CourseInfo { get; set; }
        public virtual EduType EduType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamInfo> ExamInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InClassRecord> InClassRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperInfo> PaperInfo { get; set; }
    }
}
