//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Movie_ticketingEntities : DbContext
    {
        public Movie_ticketingEntities()
            : base("name=Movie_ticketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<MovieTheater> MovieTheater { get; set; }
        public virtual DbSet<MovieTypes> MovieTypes { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
        public virtual DbSet<TeaterRelation> TeaterRelation { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
