//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.MovieTheater = new HashSet<MovieTheater>();
            this.Orders = new HashSet<Orders>();
            this.Relation = new HashSet<Relation>();
            this.TeaterRelation = new HashSet<TeaterRelation>();
        }
    
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public decimal MoviePrice { get; set; }
        public System.DateTime MovieShowDate { get; set; }
        public int MovieDuration { get; set; }
        public string MovieImage { get; set; }
        public int AreaID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string Score { get; set; }
        public string BoxOffice { get; set; }
        public int LanguageID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTheater> MovieTheater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation> Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeaterRelation> TeaterRelation { get; set; }
    }
}
